### PR TITLE
feat(core.js): pass logEntry to collapsed function

### PR DESCRIPTION
**Pull request by jedwards1211**
so that I can implement a collapse function that collapses everything but entries with errors

### CODE REVIEW

**Comment by jedwards1211** [comment]
looks like the code coverage config is too strict for the minimal amount of tests that are currently present

**Comment by evgenyrodionov** [comment]
Yeah, really too strict. @grushetsky can you update it?

@jedwards1211 why you need logEntry? Probably `action` is enough for your case?

**Comment by jedwards1211** [comment]
@evgenyrodionov well, I hadn't realized that `redux-logger` does log errors even if an action is collapsed, so I'm not sure this is necessary.  But I don't see a simple way to uncollapse actions that caused errors without access to `logEntry` or the `error`.  Otherwise I'd have to redispatch the `action` on the old `state` and see if it throws...and redispatching an action isn't kosher (could trigger side effects in middleware)

**Comment by evgenyrodionov** [comment]
Thanks!

**Pull request merged**
